##Arithmatic operator (+, -, *, /, //, %, **)
# print('Division',7/3)
# print('Floor division',7//3)
# print('Modulus',7%3)
# print('Exponentiation',7**3)

##Relational operator (>, <, >=, <=, ==, !=)
# print(5>10)
# print(5<10)
# print(5>5)
# print(5>=5)
# print(5==5)
# print(5==50)
# print(5!=5)
# print(5!=50)

##Logical operator (and, or, not)
# print(True and True)
# print(True and False)
# print(False and True)
# print(False and False)
# print(True or True)
# print(True or False)
# print(False or True)
# print(False or False)
print(not(True))
print(not False)
